name: Update CloudFlare IP List

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时运行一次
  workflow_dispatch:  # 允许手动触发
  push:
    branches: [ main, master ]
    paths:
      - 'ip_refresh.py'
      - 'config.json'
      - '.github/workflows/update-ip.yml'

jobs:
  update-ip-list:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run IP refresh script
      run: python ip_refresh.py
    
    - name: Commit and push changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Action"
        if [ -n "$(git status --porcelain)" ]; then
          git add ip.txt
          git commit -m "🔄 Auto update CloudFlare IP list ($(date '+%Y-%m-%d %H:%M:%S UTC'))"
          git push
        else
          echo "No changes detected, skipping commit."
        fi
    
    - name: Upload IP list as artifact
      uses: actions/upload-artifact@v4
      with:
        name: cloudflare-ip-list
        path: ip.txt
        retention-days: 30